export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  mode: 'Remote' | 'Hybrid' | 'Onsite';
  experience: 'Fresher' | '0-1' | '1-3' | '3-5';
  skills: string[];
  source: 'LinkedIn' | 'Naukri' | 'Indeed';
  postedDaysAgo: number;
  salaryRange: string;
  applyUrl: string;
  description: string;
}

export const jobsData: Job[] = [
  {
    id: 'job-001',
    title: 'SDE Intern',
    company: 'Amazon',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Data Structures', 'Algorithms'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹25k–₹40k/month Internship',
    applyUrl: 'https://amazon.jobs/en/jobs/intern-sde',
    description: 'Join Amazon as an SDE Intern and work on scalable systems. You will collaborate with experienced engineers on real-world projects. Strong problem-solving skills required. Great learning opportunity for freshers.'
  },
  {
    id: 'job-002',
    title: 'Graduate Engineer Trainee',
    company: 'Infosys',
    location: 'Mysore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Python', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://infosys.com/careers/get',
    description: 'Infosys is hiring Graduate Engineer Trainees for our Mysore campus. Comprehensive training program included. Work on enterprise applications and gain exposure to multiple technologies. Excellent growth opportunities.'
  },
  {
    id: 'job-003',
    title: 'Junior Backend Developer',
    company: 'Razorpay',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Node.js', 'MongoDB', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://razorpay.com/jobs/backend-dev',
    description: 'Build payment infrastructure at scale with Razorpay. Work on microservices architecture and high-throughput systems. Collaborate with product teams to deliver robust APIs. Fast-paced fintech environment.'
  },
  {
    id: 'job-004',
    title: 'Frontend Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'CSS'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://swiggy.com/careers/intern-frontend',
    description: 'Join Swiggy frontend team and build user interfaces for millions of users. Work on React-based web applications. Learn from experienced developers and contribute to production code. 6-month internship.'
  },
  {
    id: 'job-005',
    title: 'QA Intern',
    company: 'Flipkart',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Manual Testing', 'Selenium', 'Test Cases'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '₹18k–₹30k/month Internship',
    applyUrl: 'https://flipkart.com/careers/qa-intern',
    description: 'Quality Assurance internship at Flipkart. Learn testing methodologies and automation frameworks. Work with cross-functional teams to ensure product quality. Hands-on experience with real e-commerce systems.'
  },
  {
    id: 'job-006',
    title: 'Data Analyst Intern',
    company: 'PhonePe',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Excel', 'Data Visualization'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹22k–₹38k/month Internship',
    applyUrl: 'https://phonepe.com/careers/data-analyst',
    description: 'Analyze payment data and generate insights at PhonePe. Work with large datasets and create dashboards. Learn data analytics in a fast-growing fintech company. Mentorship from senior analysts provided.'
  },
  {
    id: 'job-007',
    title: 'Java Developer (0-1)',
    company: 'TCS',
    location: 'Pune',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring Boot', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://tcs.com/careers/java-developer',
    description: 'TCS is hiring Java Developers for enterprise application development. Work on Spring Boot microservices and database integration. Training provided for freshers. Opportunity to work with global clients.'
  },
  {
    id: 'job-008',
    title: 'Python Developer (Fresher)',
    company: 'Wipro',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST APIs'],
    source: 'Indeed',
    postedDaysAgo: 6,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://wipro.com/careers/python-dev',
    description: 'Join Wipro as a Python Developer and work on web applications. Learn Django framework and API development. Collaborate with international teams. Comprehensive onboarding and training program.'
  },
  {
    id: 'job-009',
    title: 'React Developer (1-3)',
    company: 'Zoho',
    location: 'Chennai',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React', 'Redux', 'TypeScript', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://zoho.com/careers/react-developer',
    description: 'Build modern web applications with React at Zoho. Work on complex UI components and state management. Collaborate with designers and backend teams. Opportunity to work on products used by millions globally.'
  },
  {
    id: 'job-010',
    title: 'Full Stack Developer',
    company: 'Freshworks',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Node.js', 'React', 'PostgreSQL', 'AWS'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://freshworks.com/careers/fullstack',
    description: 'Join Freshworks and build SaaS products for global customers. Work across the stack with modern technologies. Collaborative environment with focus on innovation. Competitive compensation and benefits.'
  },
  {
    id: 'job-011',
    title: 'DevOps Intern',
    company: 'Paytm',
    location: 'Noida',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Linux', 'Docker', 'Git', 'CI/CD'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://paytm.com/careers/devops-intern',
    description: 'Learn DevOps practices at Paytm. Work with containerization and deployment pipelines. Gain hands-on experience with cloud infrastructure. Mentorship from experienced DevOps engineers.'
  },
  {
    id: 'job-012',
    title: 'Android Developer',
    company: 'CRED',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Kotlin', 'Android SDK', 'MVVM', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://cred.club/careers/android',
    description: 'Build premium Android experiences at CRED. Work on a highly polished fintech app. Focus on performance and user experience. Collaborative team with high engineering standards.'
  },
  {
    id: 'job-013',
    title: 'Backend Engineer',
    company: 'Juspay',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Microservices', 'Kafka', 'Redis'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://juspay.in/careers/backend',
    description: 'Build payment infrastructure at Juspay. Work on high-throughput distributed systems. Handle millions of transactions daily. Strong focus on reliability and performance.'
  },
  {
    id: 'job-014',
    title: 'UI/UX Designer Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹30k/month Internship',
    applyUrl: 'https://swiggy.com/careers/design-intern',
    description: 'Design delightful user experiences at Swiggy. Work on mobile and web interfaces. Collaborate with product managers and engineers. Learn from experienced designers in a fast-paced environment.'
  },
  {
    id: 'job-015',
    title: 'Machine Learning Intern',
    company: 'Amazon',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'TensorFlow', 'Machine Learning', 'Statistics'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹30k–₹50k/month Internship',
    applyUrl: 'https://amazon.jobs/ml-intern',
    description: 'Work on cutting-edge ML projects at Amazon. Apply machine learning to real-world problems. Collaborate with research scientists and engineers. Excellent opportunity for ML enthusiasts.'
  },
  {
    id: 'job-016',
    title: 'Software Engineer',
    company: 'Accenture',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Spring', 'SQL', 'Agile'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://accenture.com/careers/swe',
    description: 'Join Accenture and work on enterprise software solutions. Exposure to multiple domains and technologies. Work with global teams on large-scale projects. Strong training and career development programs.'
  },
  {
    id: 'job-017',
    title: 'Cloud Engineer',
    company: 'IBM',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'Python'],
    source: 'Indeed',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://ibm.com/careers/cloud-engineer',
    description: 'Build cloud infrastructure solutions at IBM. Work with AWS and Kubernetes. Automate deployments and manage cloud resources. Opportunity to earn cloud certifications.'
  },
  {
    id: 'job-018',
    title: 'Data Engineer',
    company: 'Flipkart',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Python', 'Spark', 'Hadoop', 'SQL', 'Airflow'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://flipkart.com/careers/data-engineer',
    description: 'Build data pipelines at scale for Flipkart. Work with petabytes of data. Design and implement ETL workflows. Collaborate with data scientists and analysts.'
  },
  {
    id: 'job-019',
    title: 'Frontend Developer',
    company: 'Capgemini',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://capgemini.com/careers/frontend',
    description: 'Develop responsive web applications at Capgemini. Work on client projects across industries. Learn modern frontend frameworks. Opportunity for international exposure.'
  },
  {
    id: 'job-020',
    title: 'iOS Developer',
    company: 'Razorpay',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Swift', 'iOS SDK', 'UIKit', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://razorpay.com/careers/ios',
    description: 'Build iOS applications for Razorpay payment platform. Work on native iOS development with Swift. Focus on performance and user experience. Collaborative fintech environment.'
  },
  {
    id: 'job-021',
    title: 'Security Analyst Intern',
    company: 'Cognizant',
    location: 'Chennai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Cybersecurity', 'Network Security', 'Linux'],
    source: 'Naukri',
    postedDaysAgo: 9,
    salaryRange: '₹18k–₹32k/month Internship',
    applyUrl: 'https://cognizant.com/careers/security-intern',
    description: 'Learn cybersecurity practices at Cognizant. Work on security assessments and vulnerability analysis. Gain exposure to enterprise security tools. Training and certification support provided.'
  },
  {
    id: 'job-022',
    title: 'Product Manager Intern',
    company: 'PhonePe',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Product Management', 'Analytics', 'Communication'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹25k–₹40k/month Internship',
    applyUrl: 'https://phonepe.com/careers/pm-intern',
    description: 'Join PhonePe product team and learn product management. Work on feature development and user research. Collaborate with engineering and design teams. Great opportunity for aspiring PMs.'
  },
  {
    id: 'job-023',
    title: 'SAP Consultant',
    company: 'SAP',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['SAP', 'ABAP', 'S/4HANA', 'Business Process'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://sap.com/careers/consultant',
    description: 'Implement SAP solutions for enterprise clients. Work on S/4HANA projects and customizations. Travel opportunities for client engagements. Comprehensive SAP training provided.'
  },
  {
    id: 'job-024',
    title: 'Salesforce Developer',
    company: 'Accenture',
    location: 'Pune',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Salesforce', 'Apex', 'Lightning', 'CRM'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://accenture.com/careers/salesforce',
    description: 'Develop Salesforce solutions for global clients. Work on CRM implementations and customizations. Opportunity to earn Salesforce certifications. Work with experienced Salesforce architects.'
  },
  {
    id: 'job-025',
    title: 'Business Analyst',
    company: 'Oracle',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Business Analysis', 'SQL', 'Requirements Gathering'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://oracle.com/careers/ba',
    description: 'Analyze business requirements and design solutions at Oracle. Work with stakeholders to gather and document requirements. Bridge the gap between business and technology teams.'
  },
  {
    id: 'job-026',
    title: 'Test Automation Engineer',
    company: 'Dell',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Selenium', 'Java', 'TestNG', 'CI/CD'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://dell.com/careers/qa-automation',
    description: 'Build test automation frameworks at Dell. Work on continuous testing and integration. Improve software quality through automated testing. Collaborative global team environment.'
  },
  {
    id: 'job-027',
    title: 'Network Engineer',
    company: 'Cisco',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Networking', 'Cisco', 'Routing', 'Switching'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://cisco.com/careers/network-engineer',
    description: 'Design and implement network solutions at Cisco. Work on enterprise networking projects. Opportunity to earn Cisco certifications. Exposure to cutting-edge networking technologies.'
  },
  {
    id: 'job-028',
    title: 'Content Writer Intern',
    company: 'Zoho',
    location: 'Chennai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Technical Writing', 'Content Creation', 'Communication'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹25k/month Internship',
    applyUrl: 'https://zoho.com/careers/content-writer',
    description: 'Create technical content and documentation at Zoho. Write blog posts, tutorials, and product documentation. Learn technical writing best practices. Work with product and marketing teams.'
  },
  {
    id: 'job-029',
    title: 'Blockchain Developer',
    company: 'TechCorp',
    location: 'Bangalore',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Solidity', 'Ethereum', 'Web3', 'Smart Contracts'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://techcorp.io/careers/blockchain',
    description: 'Build decentralized applications and smart contracts. Work on blockchain infrastructure and Web3 projects. Cutting-edge technology stack. Fully remote position with flexible hours.'
  },
  {
    id: 'job-030',
    title: 'Site Reliability Engineer',
    company: 'Flipkart',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Linux', 'Kubernetes', 'Monitoring', 'Python'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://flipkart.com/careers/sre',
    description: 'Ensure reliability and performance of Flipkart infrastructure. Work on monitoring, alerting, and incident response. Automate operational tasks. On-call rotation with competitive compensation.'
  },
  {
    id: 'job-031',
    title: 'Game Developer Intern',
    company: 'GameStudio',
    location: 'Pune',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Unity', 'C#', 'Game Design', '3D Graphics'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://gamestudio.in/careers/intern',
    description: 'Develop mobile and PC games using Unity. Work on gameplay mechanics and graphics. Learn game development from experienced developers. Portfolio-building opportunity.'
  },
  {
    id: 'job-032',
    title: 'Embedded Systems Engineer',
    company: 'Bosch',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['C', 'Embedded C', 'Microcontrollers', 'RTOS'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://bosch.com/careers/embedded',
    description: 'Work on embedded systems for automotive applications. Develop firmware for microcontrollers. Work with hardware teams on product development. Global company with strong engineering culture.'
  },
  {
    id: 'job-033',
    title: 'Digital Marketing Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SEO', 'Social Media', 'Google Analytics', 'Content Marketing'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹28k/month Internship',
    applyUrl: 'https://swiggy.com/careers/marketing-intern',
    description: 'Learn digital marketing at Swiggy. Work on SEO, social media campaigns, and content strategy. Analyze marketing metrics and optimize campaigns. Fast-paced consumer tech environment.'
  },
  {
    id: 'job-034',
    title: 'ETL Developer',
    company: 'Infosys',
    location: 'Pune',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Informatica', 'SQL', 'Data Warehousing', 'ETL'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://infosys.com/careers/etl',
    description: 'Design and develop ETL processes for data warehousing projects. Work with Informatica and SQL. Handle data integration from multiple sources. Work with global clients.'
  },
  {
    id: 'job-035',
    title: 'React Native Developer',
    company: 'CRED',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React Native', 'JavaScript', 'Mobile Development', 'Redux'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://cred.club/careers/react-native',
    description: 'Build cross-platform mobile applications at CRED. Work on both iOS and Android using React Native. Focus on performance and user experience. Premium fintech product with high standards.'
  },
  {
    id: 'job-036',
    title: 'Technical Support Engineer',
    company: 'Freshworks',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Technical Support', 'Troubleshooting', 'Customer Service'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://freshworks.com/careers/support',
    description: 'Provide technical support to Freshworks customers globally. Troubleshoot product issues and guide customers. Work with engineering teams on bug fixes. Great entry point into SaaS industry.'
  },
  {
    id: 'job-037',
    title: 'AI/ML Engineer',
    company: 'Juspay',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'NLP'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://juspay.in/careers/ml-engineer',
    description: 'Apply machine learning to payment fraud detection and risk assessment. Work on NLP and predictive models. Research-oriented environment. Opportunity to publish papers.'
  },
  {
    id: 'job-038',
    title: 'Database Administrator',
    company: 'TCS',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Oracle', 'MySQL', 'PostgreSQL', 'Database Tuning'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://tcs.com/careers/dba',
    description: 'Manage and optimize databases for enterprise applications. Handle database performance tuning and backup strategies. Work on high-availability database systems. 24/7 support rotation.'
  },
  {
    id: 'job-039',
    title: 'Scrum Master',
    company: 'Wipro',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Agile', 'Scrum', 'Jira', 'Team Management'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://wipro.com/careers/scrum-master',
    description: 'Facilitate agile ceremonies and remove team impediments. Coach teams on agile best practices. Work with multiple scrum teams. CSM certification preferred but not mandatory.'
  },
  {
    id: 'job-040',
    title: 'Flutter Developer',
    company: 'PayU',
    location: 'Gurgaon',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Flutter', 'Dart', 'Mobile Development', 'REST APIs'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://payu.in/careers/flutter',
    description: 'Build cross-platform payment applications using Flutter. Work on fintech products for Indian and international markets. Fully remote position. Collaborative team with modern tech stack.'
  },
  {
    id: 'job-041',
    title: 'Graphic Designer Intern',
    company: 'Razorpay',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Adobe Photoshop', 'Illustrator', 'Design', 'Branding'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '₹18k–₹30k/month Internship',
    applyUrl: 'https://razorpay.com/careers/design-intern',
    description: 'Create visual designs for marketing and product teams. Work on brand identity and marketing collateral. Learn from experienced designers. Portfolio-building opportunity in fintech.'
  },
  {
    id: 'job-042',
    title: 'Technical Writer',
    company: 'Amazon',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Technical Writing', 'Documentation', 'API Documentation'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://amazon.jobs/tech-writer',
    description: 'Create technical documentation for AWS services. Write API documentation and developer guides. Work with engineering teams to understand complex systems. Strong writing skills required.'
  },
  {
    id: 'job-043',
    title: 'Performance Engineer',
    company: 'PhonePe',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['JMeter', 'Performance Testing', 'Load Testing', 'Monitoring'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://phonepe.com/careers/performance',
    description: 'Ensure application performance under high load. Conduct load testing and identify bottlenecks. Work on performance optimization strategies. Critical role in high-traffic fintech platform.'
  },
  {
    id: 'job-044',
    title: 'Java Full Stack Developer',
    company: 'Cognizant',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'Angular', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://cognizant.com/careers/fullstack-java',
    description: 'Develop end-to-end web applications using Java and Angular. Work on enterprise projects for global clients. Exposure to full software development lifecycle. Training and upskilling opportunities.'
  },
  {
    id: 'job-045',
    title: 'Cybersecurity Engineer',
    company: 'Paytm',
    location: 'Noida',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Security', 'Penetration Testing', 'OWASP', 'Firewall'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://paytm.com/careers/security',
    description: 'Protect Paytm infrastructure from security threats. Conduct security audits and penetration testing. Implement security best practices. Work with compliance and engineering teams.'
  },
  {
    id: 'job-046',
    title: 'Data Scientist',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Python', 'Machine Learning', 'Statistics', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://swiggy.com/careers/data-scientist',
    description: 'Build predictive models for delivery optimization and demand forecasting. Work with large datasets. Collaborate with product and engineering teams. Impact millions of users daily.'
  },
  {
    id: 'job-047',
    title: 'Automation Tester',
    company: 'Capgemini',
    location: 'Pune',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Selenium', 'Java', 'Automation Testing', 'TestNG'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://capgemini.com/careers/automation-tester',
    description: 'Automate test cases for web applications. Work on test automation frameworks. Collaborate with development teams. Training provided for freshers with testing interest.'
  },
  {
    id: 'job-048',
    title: 'Solutions Architect',
    company: 'IBM',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '3-5',
    skills: ['Cloud Architecture', 'AWS', 'System Design', 'Microservices'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://ibm.com/careers/architect',
    description: 'Design cloud-based solutions for enterprise clients. Work on architecture design and technology selection. Lead technical discussions with stakeholders. Opportunity to work on large-scale projects.'
  },
  {
    id: 'job-049',
    title: 'Mobile QA Engineer',
    company: 'CRED',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Mobile Testing', 'Appium', 'iOS', 'Android'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://cred.club/careers/mobile-qa',
    description: 'Ensure quality of CRED mobile applications. Test on multiple devices and OS versions. Automate mobile test cases. Work with developers to maintain high quality standards.'
  },
  {
    id: 'job-050',
    title: 'Backend Developer Intern',
    company: 'Zoho',
    location: 'Chennai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'MySQL', 'REST APIs'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://zoho.com/careers/backend-intern',
    description: 'Learn backend development at Zoho. Work on Java-based web services. Gain hands-on experience with databases and APIs. Mentorship from senior engineers. Potential for full-time conversion.'
  },
  {
    id: 'job-051',
    title: 'Product Designer',
    company: 'Flipkart',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['UI/UX', 'Figma', 'User Research', 'Prototyping'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://flipkart.com/careers/product-designer',
    description: 'Design user experiences for Flipkart e-commerce platform. Conduct user research and create prototypes. Work closely with product managers and engineers. Impact millions of users.'
  },
  {
    id: 'job-052',
    title: 'System Administrator',
    company: 'Dell',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Linux', 'Windows Server', 'Networking', 'Scripting'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://dell.com/careers/sysadmin',
    description: 'Manage and maintain IT infrastructure at Dell. Handle server administration and troubleshooting. Automate routine tasks with scripting. Work with global IT teams.'
  },
  {
    id: 'job-053',
    title: 'Angular Developer',
    company: 'Accenture',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Angular', 'TypeScript', 'RxJS', 'REST APIs'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://accenture.com/careers/angular',
    description: 'Build enterprise web applications using Angular. Work on large-scale projects for global clients. Collaborate with international teams. Opportunity for client-facing roles.'
  },
  {
    id: 'job-054',
    title: 'Go Developer',
    company: 'Juspay',
    location: 'Bangalore',
    mode: 'Remote',
    experience: '1-3',
    skills: ['Golang', 'Microservices', 'Docker', 'Kubernetes'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://juspay.in/careers/golang',
    description: 'Build high-performance microservices in Go. Work on payment infrastructure at scale. Fully remote position. Modern tech stack and engineering practices.'
  },
  {
    id: 'job-055',
    title: 'HR Intern',
    company: 'Infosys',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['HR', 'Recruitment', 'Communication', 'MS Office'],
    source: 'Naukri',
    postedDaysAgo: 9,
    salaryRange: '₹15k–₹25k/month Internship',
    applyUrl: 'https://infosys.com/careers/hr-intern',
    description: 'Support HR operations and recruitment activities. Learn talent acquisition and employee engagement. Work with HR team on various initiatives. Good opportunity for HR career starters.'
  },
  {
    id: 'job-056',
    title: 'Finance Analyst Intern',
    company: 'Razorpay',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Finance', 'Excel', 'Financial Modeling', 'Analytics'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://razorpay.com/careers/finance-intern',
    description: 'Analyze financial data and create reports. Work on financial modeling and forecasting. Learn fintech business operations. Exposure to fast-growing startup environment.'
  },
  {
    id: 'job-057',
    title: 'Video Editor Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Video Editing', 'Adobe Premiere', 'After Effects', 'Storytelling'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹18k–₹30k/month Internship',
    applyUrl: 'https://swiggy.com/careers/video-editor',
    description: 'Create video content for marketing campaigns. Edit promotional videos and social media content. Work with creative team. Build portfolio in consumer tech space.'
  },
  {
    id: 'job-058',
    title: 'Legal Intern',
    company: 'PhonePe',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Legal Research', 'Contract Review', 'Compliance'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '₹20k–₹35k/month Internship',
    applyUrl: 'https://phonepe.com/careers/legal-intern',
    description: 'Support legal team with research and documentation. Review contracts and compliance matters. Learn fintech regulations. Exposure to fast-paced legal environment.'
  },
  {
    id: 'job-059',
    title: 'Operations Manager',
    company: 'Flipkart',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Operations', 'Logistics', 'Process Improvement', 'Analytics'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://flipkart.com/careers/operations',
    description: 'Manage warehouse and logistics operations. Optimize supply chain processes. Work with cross-functional teams. Fast-paced e-commerce environment with growth opportunities.'
  },
  {
    id: 'job-060',
    title: 'Customer Success Manager',
    company: 'Freshworks',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Customer Success', 'Communication', 'CRM', 'Problem Solving'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://freshworks.com/careers/csm',
    description: 'Ensure customer satisfaction and product adoption. Work with enterprise clients globally. Drive renewals and upsells. Great opportunity in SaaS customer success.'
  }
];
